# Generated by Django 5.0.2 on 2024-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('shorten_url', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shorten URL',
                'verbose_name_plural': 'Shorten URLs',
                'db_table': 'shortener_url',
                'ordering': ['-created_at'],
            },
        ),
    ]
