# Generated by Django 5.0.2 on 2024-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('access_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ip_address', 'access_date')},
            },
        ),
    ]
