# Generated by Django 5.0.2 on 2025-04-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='shorten_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterModelTable(
            name='accesslog',
            table='shortener_access_log',
        ),
    ]
