services:
  shortener_web:
    container_name: shortener_web
    build: .
    restart: always
    env_file:
      - ./application/.env
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - traefik-network
      - main-redis-network
      - postgres-network
    environment:
      - TZ=Asia/Seoul
    labels:
      # 공통 Traefik 설정
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      
      # dev.wenivops.co.kr/services/shortener 엔드포인트 설정
#      - "traefik.http.routers.shortener-dev.rule=Host(`dev.wenivops.co.kr`) && PathPrefix(`/services/shortener`)"
#      - "traefik.http.routers.shortener-dev.entrypoints=websecure"
#      - "traefik.http.routers.shortener-dev.tls=true"
#      - "traefik.http.routers.shortener-dev.tls.certresolver=myresolver"
#      - "traefik.http.middlewares.shortener-dev-stripprefix.stripprefix.prefixes=/services/shortener"
#      - "traefik.http.routers.shortener-dev.middlewares=shortener-dev-stripprefix"
#      - "traefik.http.services.shortener-dev.loadbalancer.server.port=9103"

      # weniv.link 엔드포인트 설정
      - "traefik.http.routers.shortener-live.rule=Host(`weniv.link`)"
      - "traefik.http.routers.shortener-live.entrypoints=websecure"
      - "traefik.http.routers.shortener-live.tls=true"
      - "traefik.http.routers.shortener-live.tls.certresolver=myresolver"
#      - "traefik.http.middlewares.shortener-live-stripprefix.stripprefix.prefixes=/"
#      - "traefik.http.routers.shortener-live.middlewares=shortener-live-stripprefix"
      - "traefik.http.services.shortener-live.loadbalancer.server.port=9103"

  shortener_nginx:
    container_name: shortener_nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - shortener_web
    networks:
      - traefik-network
    labels:
      # Traefik 설정 (Nginx로 라우팅)
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      
      # 정적 파일 서빙 설정
      - "traefik.http.routers.shortener-static.rule=Host(`weniv.link`) && PathPrefix(`/static/`)"
      - "traefik.http.routers.shortener-static.entrypoints=websecure"
      - "traefik.http.routers.shortener-static.tls=true"
      - "traefik.http.routers.shortener-static.tls.certresolver=myresolver"
      - "traefik.http.middlewares.shortener-static-stripprefix.stripprefix.prefixes=/static/"
      - "traefik.http.routers.shortener-static.middlewares=shortener-static-stripprefix"
      - "traefik.http.services.shortener-static.loadbalancer.server.port=80"

#      - "traefik.http.routers.shortener-static-dev.rule=Host(`dev.wenivops.co.kr`) && PathPrefix(`/services/shortener/static/`)"
#      - "traefik.http.routers.shortener-static-dev.entrypoints=websecure"
#      - "traefik.http.routers.shortener-static-dev.tls=true"
#      - "traefik.http.routers.shortener-static-dev.tls.certresolver=myresolver"
#      - "traefik.http.routers.shortener-static-dev.middlewares=shortener-static-dev-stripprefix"
#      - "traefik.http.middlewares.shortener-static-dev-stripprefix.stripprefix.prefixes=/services/shortener"
#      - "traefik.http.services.shortener-static-dev.loadbalancer.server.port=80"

volumes:
  static_volume:
    name: shortener_static_volume

networks:
  traefik-network:
    external: true
  main-redis-network:
    external: true
  postgres-network:
    external: true