version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/web

    working_dir: /web/

    command: >
      && ./wait-for-it.sh db:5432 -t 10
      && python3 manage.py makemigrations
      && python3 manage.py migrate 
      && python3 manage.py runserver"
    ports:
      - "8000:8000"

    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data


    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
