version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    working_dir: /usr/src/app/

#    command: ./entrypoint.sh
    ports:
      - "8000:8000"

    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data

    networks:
      - postgres

    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - LANG=UTF-8
    expose:
      - "5433"
    ports:
      - "5432:5433"

networks:
  postgres:
    driver: bridge