# Generated by Django 4.2.4 on 2023-08-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "originalUrl",
                    models.URLField(db_column="original_url", max_length=255),
                ),
                (
                    "shortUrl",
                    models.URLField(db_column="short_url", max_length=100, null=True),
                ),
            ],
        ),
    ]
