# Generated by Django 4.2.4 on 2023-08-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_shortener_url",
            "0002_rename_originalurl_shortener_original_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortener",
            name="short_url",
            field=models.URLField(db_column="short_url", default="", max_length=100),
        ),
    ]
