# Generated by Django 4.2.4 on 2023-08-25 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_shortener_url", "0003_alter_shortener_short_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortener",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="shortener",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
