# Generated by Django 4.2.4 on 2023-08-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_shortener_url", "0004_alter_shortener_options_shortener_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortener",
            name="visit_count",
            field=models.IntegerField(default=0),
        ),
    ]
