# Generated by Django 4.2.4 on 2023-08-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_shortener_url", "0005_shortener_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortener",
            name="hash_key",
            field=models.BigIntegerField(db_column="hash_key", default=1),
            preserve_default=False,
        ),
    ]
