name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 서버에 SSH로 접속하여 배포
    - name: Deploy to Dev Server
      if: github.event_name != 'pull_request'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ~/projects/weniv_shortener_url
          git pull
          docker compose down
          docker compose build
          docker compose up -d
          
          # 배포 결과 확인
          echo "Deployment completed at $(date)"
          docker compose ps
